package com.yuralex.poketool;

import android.util.SparseArray;

/**
 *
 * Created by heiderlopes on 11/12/14.
 */
class DaoPokemon {
    SparseArray<PokemonImg> getAllPokemon() {
        SparseArray<PokemonImg> pokemons = new SparseArray<>();

        pokemons.put(1, new PokemonImg(1, "Bulbasaur", "Grama", R.drawable.p001_bulbasaur));
        pokemons.put(2, new PokemonImg(2, "Ivysaur", "", R.drawable.p002_ivysaur));
        pokemons.put(3, new PokemonImg(3, "Venusaur", "", R.drawable.p003_venusaur));
        pokemons.put(4, new PokemonImg(4, "Charmander", "", R.drawable.p004_charmander));
        pokemons.put(5, new PokemonImg(5, "Charmeleon", "", R.drawable.p005_charmeleon));
        pokemons.put(6, new PokemonImg(6, "Charizard", "", R.drawable.p006_charizard));
        pokemons.put(7, new PokemonImg(7, "Squirle", "", R.drawable.p007_squirtle));
        pokemons.put(8, new PokemonImg(8, "Wartotle", "", R.drawable.p008_wartotle));
        pokemons.put(9, new PokemonImg(9, "Blastoise", "", R.drawable.p009_blastoise));
        pokemons.put(10, new PokemonImg(10, "Caterpie", "", R.drawable.p010_caterpie));
        pokemons.put(11, new PokemonImg(11, "Metapod", "", R.drawable.p011_metapod));
        pokemons.put(12, new PokemonImg(12, "Butterfree", "", R.drawable.p012_butterfree));
        pokemons.put(13, new PokemonImg(13, "Weedle", "", R.drawable.p013_weedle));
        pokemons.put(14, new PokemonImg(14, "Kakuna", "", R.drawable.p014_kakuna));
        pokemons.put(15, new PokemonImg(15, "Beedrill", "", R.drawable.p015_beedrill));
        pokemons.put(16, new PokemonImg(16, "Pidgey", "", R.drawable.p016_pidgey));
        pokemons.put(17, new PokemonImg(17, "Pidgeotto", "", R.drawable.p017_pidgeotto));
        pokemons.put(18, new PokemonImg(18, "Pidgeot", "", R.drawable.p018_pidgeot));
        pokemons.put(19, new PokemonImg(19, "Rattata", "", R.drawable.p019_rattata));
        pokemons.put(20, new PokemonImg(20, "Raticate", "", R.drawable.p020_raticate));
        pokemons.put(21, new PokemonImg(21, "Spearow", "", R.drawable.p021_spearow));
        pokemons.put(22, new PokemonImg(22, "Fearow", "", R.drawable.p022_fearow));
        pokemons.put(23, new PokemonImg(23, "Ekans", "", R.drawable.p023_ekans));
        pokemons.put(24, new PokemonImg(24, "Arbok", "", R.drawable.p024_arbok));
        pokemons.put(25, new PokemonImg(25, "Pikachu", "", R.drawable.p025_pikachu));
        pokemons.put(26, new PokemonImg(26, "Raichu", "", R.drawable.p026_raichu));
        pokemons.put(27, new PokemonImg(27, "Sandshrew", "", R.drawable.p027_sandshrew));
        pokemons.put(28, new PokemonImg(28, "Sandslash", "", R.drawable.p028_sandslash));
        pokemons.put(29, new PokemonImg(29, "Nidoram Femea", "", R.drawable.p029_nidoran_femea));
        pokemons.put(30, new PokemonImg(30, "Nidorina", "", R.drawable.p030_nidorina));
        pokemons.put(31, new PokemonImg(31, "Nidoqueen", "", R.drawable.p031_nidoqueen));
        pokemons.put(32, new PokemonImg(32, "Nidoran Macho", "", R.drawable.p032_nidoran_macho));
        pokemons.put(33, new PokemonImg(33, "Nidorino", "", R.drawable.p033_nidorino));
        pokemons.put(34, new PokemonImg(34, "Nidoking", "", R.drawable.p034_nidoking));
        pokemons.put(35, new PokemonImg(35, "Clefairy", "", R.drawable.p035_clefairy));
        pokemons.put(36, new PokemonImg(36, "Clefable", "", R.drawable.p036_clefable));
        pokemons.put(37, new PokemonImg(37, "Vulpix", "", R.drawable.p037_vulpix));
        pokemons.put(38, new PokemonImg(38, "Ninetales", "", R.drawable.p038_ninetales));
        pokemons.put(39, new PokemonImg(39, "Jigglypuff", "", R.drawable.p039_jigglypuff));
        pokemons.put(40, new PokemonImg(40, "Wigglytuff", "", R.drawable.p040_wigglytuff));
        pokemons.put(41, new PokemonImg(41, "Zubat", "", R.drawable.p041_zubat));
        pokemons.put(42, new PokemonImg(42, "Golbat", "", R.drawable.p042_golbat));
        pokemons.put(43, new PokemonImg(43, "Oddish", "", R.drawable.p043_oddish));
        pokemons.put(44, new PokemonImg(44, "Gloom", "", R.drawable.p044_gloom));
        pokemons.put(45, new PokemonImg(45, "Vileplume", "", R.drawable.p045_vileplume));
        pokemons.put(46, new PokemonImg(46, "Paras", "", R.drawable.p046_paras));
        pokemons.put(47, new PokemonImg(47, "Parasect", "", R.drawable.p047_parasect));
        pokemons.put(48, new PokemonImg(48, "Venonat", "", R.drawable.p048_venonat));
        pokemons.put(49, new PokemonImg(49, "Venomoth", "", R.drawable.p049_venomoth));
        pokemons.put(50, new PokemonImg(50, "Diglett", "", R.drawable.p050_diglett));
        pokemons.put(51, new PokemonImg(51, "Dugtrio", "", R.drawable.p051_dugtrio));
        pokemons.put(52, new PokemonImg(52, "Meowth", "", R.drawable.p052_meowth));
        pokemons.put(53, new PokemonImg(53, "Persian", "", R.drawable.p053_persian));
        pokemons.put(54, new PokemonImg(54, "Psyduck", "", R.drawable.p054_psyduck));
        pokemons.put(55, new PokemonImg(55, "Golduck", "", R.drawable.p055_golduck));
        pokemons.put(56, new PokemonImg(56, "Mankey", "", R.drawable.p056_mankey));
        pokemons.put(57, new PokemonImg(57, "Primeape", "", R.drawable.p057_primeap));
        pokemons.put(58, new PokemonImg(58, "Growlithe", "", R.drawable.p058_growlithe));
        pokemons.put(59, new PokemonImg(59, "Arcanine", "", R.drawable.p059_arcanine));
        pokemons.put(60, new PokemonImg(60, "Poliwag", "", R.drawable.p060_poliwag));
        pokemons.put(61, new PokemonImg(61, "Poliwhirl", "", R.drawable.p061_poliwhirl));
        pokemons.put(62, new PokemonImg(62, "Poliwrath", "", R.drawable.p062_poliwrath));
        pokemons.put(63, new PokemonImg(63, "Abra", "", R.drawable.p063_abra));
        pokemons.put(64, new PokemonImg(64, "Kadabra", "", R.drawable.p064_kadabra));
        pokemons.put(65, new PokemonImg(65, "Alakazam", "", R.drawable.p065_alakazam));
        pokemons.put(66, new PokemonImg(66, "Machop", "", R.drawable.p066_machop));
        pokemons.put(67, new PokemonImg(67, "Machoke", "", R.drawable.p067_machoke));
        pokemons.put(68, new PokemonImg(68, "Machamp", "", R.drawable.p068_machamp));
        pokemons.put(69, new PokemonImg(69, "Bellsprout", "", R.drawable.p069_bellsprout));
        pokemons.put(70, new PokemonImg(70, "Weepinbell", "", R.drawable.p070_weepinbell));
        pokemons.put(71, new PokemonImg(71, "Victreebel", "", R.drawable.p071_victreebel));
        pokemons.put(72, new PokemonImg(72, "Tentacool", "", R.drawable.p072_tentacool));
        pokemons.put(73, new PokemonImg(73, "Tentacruel", "", R.drawable.p073_tentacruel));
        pokemons.put(74, new PokemonImg(74, "Geodude", "", R.drawable.p074_geodude));
        pokemons.put(75, new PokemonImg(75, "Graveler", "", R.drawable.p075_graveler));
        pokemons.put(76, new PokemonImg(76, "Golem", "", R.drawable.p076_golem));
        pokemons.put(77, new PokemonImg(77, "Ponyta", "", R.drawable.p077_ponyta));
        pokemons.put(78, new PokemonImg(78, "Rapidash", "", R.drawable.p078_rapidash));
        pokemons.put(79, new PokemonImg(79, "Slowpoke", "", R.drawable.p079_slowpoke));
        pokemons.put(80, new PokemonImg(80, "Slowbro", "", R.drawable.p080_slowbro));
        pokemons.put(81, new PokemonImg(81, "Magnemite", "", R.drawable.p081_magnemite));
        pokemons.put(82, new PokemonImg(82, "Magneton", "", R.drawable.p082_magneton));
        pokemons.put(83, new PokemonImg(83, "Farfetch'd", "", R.drawable.p083_farfetchd));
        pokemons.put(84, new PokemonImg(84, "Doduo", "", R.drawable.p084_doduo));
        pokemons.put(85, new PokemonImg(85, "Dodrio", "", R.drawable.p085_dodrio));
        pokemons.put(86, new PokemonImg(86, "Seel", "", R.drawable.p086_seel));
        pokemons.put(87, new PokemonImg(87, "Dewgong", "", R.drawable.p087_dewgong));
        pokemons.put(88, new PokemonImg(88, "Grimer", "", R.drawable.p088_grimer));
        pokemons.put(89, new PokemonImg(89, "Muk", "", R.drawable.p089_muk));
        pokemons.put(90, new PokemonImg(90, "Shellder", "", R.drawable.p090_shellder));
        pokemons.put(91, new PokemonImg(91, "Cloyster", "", R.drawable.p091_cloyster));
        pokemons.put(92, new PokemonImg(92, "Gastly", "", R.drawable.p092_gastly));
        pokemons.put(93, new PokemonImg(93, "Haunter", "", R.drawable.p093_haunter));
        pokemons.put(94, new PokemonImg(94, "Gengar", "", R.drawable.p094_gengar));
        pokemons.put(95, new PokemonImg(95, "Onix", "", R.drawable.p095_onix));
        pokemons.put(96, new PokemonImg(96, "Drowzee", "", R.drawable.p096_drowzee));
        pokemons.put(97, new PokemonImg(97, "Hypno", "", R.drawable.p097_hypno));
        pokemons.put(98, new PokemonImg(98, "Krabby", "", R.drawable.p098_krabby));
        pokemons.put(99, new PokemonImg(99, "Kingler", "", R.drawable.p099_kingler));
        pokemons.put(100, new PokemonImg(100, "Voltorb", "", R.drawable.p100_voltorb));
        pokemons.put(101, new PokemonImg(101, "Electrode", "", R.drawable.p101_electrode));
        pokemons.put(102, new PokemonImg(102, "Exeggcute", "", R.drawable.p102_exeggcute));
        pokemons.put(103, new PokemonImg(103, "Exeggutor", "", R.drawable.p103_exeggutor));
        pokemons.put(104, new PokemonImg(104, "Cubone", "", R.drawable.p104_cubone));
        pokemons.put(105, new PokemonImg(105, "Marowak", "", R.drawable.p105_marowak));
        pokemons.put(106, new PokemonImg(106, "Hitmonlee", "", R.drawable.p106_hitmonlee));
        pokemons.put(107, new PokemonImg(107, "Hitmonchan", "", R.drawable.p107_hitmonchan));
        pokemons.put(108, new PokemonImg(108, "Lickitung", "", R.drawable.p108_lickitung));
        pokemons.put(109, new PokemonImg(109, "Koffing", "", R.drawable.p109_koffing));
        pokemons.put(110, new PokemonImg(110, "Weezing", "", R.drawable.p110_weezing));
        pokemons.put(111, new PokemonImg(111, "Rhyhorn", "", R.drawable.p111_rhyhorn));
        pokemons.put(112, new PokemonImg(112, "Rhydon", "", R.drawable.p112_rhydon));
        pokemons.put(113, new PokemonImg(113, "Chansey", "", R.drawable.p113_chansey));
        pokemons.put(114, new PokemonImg(114, "Tangela", "", R.drawable.p114_tangela));
        pokemons.put(115, new PokemonImg(115, "Kangaskhan", "", R.drawable.p115_kangaskhan));
        pokemons.put(116, new PokemonImg(116, "Horsea", "", R.drawable.p116_horsea));
        pokemons.put(117, new PokemonImg(117, "Seadra", "", R.drawable.p117_seadra));
        pokemons.put(118, new PokemonImg(118, "Goldeen", "", R.drawable.p118_goldeen));
        pokemons.put(119, new PokemonImg(119, "Seaking", "", R.drawable.p119_seaking));
        pokemons.put(120, new PokemonImg(120, "Staryu", "", R.drawable.p120_staryu));
        pokemons.put(121, new PokemonImg(121, "Starmie", "", R.drawable.p121_starmie));
        pokemons.put(122, new PokemonImg(122, "Mr Mime", "", R.drawable.p122_mr_mime));
        pokemons.put(123, new PokemonImg(123, "Scyther", "", R.drawable.p123_scyther));
        pokemons.put(124, new PokemonImg(124, "Jynx", "", R.drawable.p124_jynx));
        pokemons.put(125, new PokemonImg(125, "Electabuzz", "", R.drawable.p125_elctabuzz));
        pokemons.put(126, new PokemonImg(126, "Magmar", "", R.drawable.p126_magmar));
        pokemons.put(127, new PokemonImg(127, "Pinsir", "", R.drawable.p127_pinsir));
        pokemons.put(128, new PokemonImg(128, "Taurus", "", R.drawable.p128_taurus));
        pokemons.put(129, new PokemonImg(129, "Magikarp", "", R.drawable.p129_magikarp));
        pokemons.put(130, new PokemonImg(130, "Gyrados", "", R.drawable.p130_gyarados));
        pokemons.put(131, new PokemonImg(131, "Lapras", "", R.drawable.p131_lapras));
        pokemons.put(132, new PokemonImg(132, "Ditto", "", R.drawable.p132_ditto));
        pokemons.put(133, new PokemonImg(133, "Eevee", "", R.drawable.p133_eevee));
        pokemons.put(134, new PokemonImg(134, "Vaporeon", "", R.drawable.p134_vaporeon));
        pokemons.put(135, new PokemonImg(135, "Jolteon", "", R.drawable.p135_jolteon));
        pokemons.put(136, new PokemonImg(136, "Flareon", "", R.drawable.p136_flareon));
        pokemons.put(137, new PokemonImg(137, "Porygon", "", R.drawable.p137_porygon));
        pokemons.put(138, new PokemonImg(138, "Omanyte", "", R.drawable.p138_omanyte));
        pokemons.put(139, new PokemonImg(139, "Omastar", "", R.drawable.p139_omastar));
        pokemons.put(140, new PokemonImg(140, "Kabuto", "", R.drawable.p140_kabuto));
        pokemons.put(141, new PokemonImg(141, "Kabutops", "", R.drawable.p141_kabutops));
        pokemons.put(142, new PokemonImg(142, "Aerodactyl", "", R.drawable.p142_aerodactyl));
        pokemons.put(143, new PokemonImg(143, "Snorlax", "", R.drawable.p143_snorlax));
        pokemons.put(144, new PokemonImg(144, "Articuno", "", R.drawable.p144_articuno));
        pokemons.put(145, new PokemonImg(145, "Zapdos", "", R.drawable.p145_zapdos));
        pokemons.put(146, new PokemonImg(146, "Moltres", "", R.drawable.p146_moltres));
        pokemons.put(147, new PokemonImg(147, "Dratini", "", R.drawable.p147_dratini));
        pokemons.put(148, new PokemonImg(148, "Dragonair", "", R.drawable.p148_dragonair));
        pokemons.put(149, new PokemonImg(149, "Dragonite", "", R.drawable.p149_dragonite));
        pokemons.put(150, new PokemonImg(150, "Mewtwo", "", R.drawable.p150_mewtwo));
        pokemons.put(151, new PokemonImg(151, "Mew", "", R.drawable.p151_mew));

        return pokemons;
    }
}
